import { writeFile } from 'node:fs/promises'
import type { GenerationResult } from '../../generate/types.js'
import type { DatabaseSchema } from '../../types/schema.js'
import type { OutputOptions, InsertionSummary, SequenceResetInfo } from '../types.js'
import { OutputMode } from '../types.js'
import type { ProgressReporter } from '../progress.js'
import { buildBatchedInserts } from '../batcher.js'
import { buildUpdateSQL, buildSequenceResetSQL } from '../sql-builder.js'
import { InsertionError } from '../../errors/index.js'

/**
 * Write all INSERT statements to a SQL file on disk.
 *
 * Produces a self-contained SQL file with header comments, transaction blocks,
 * INSERT batches, deferred UPDATEs, and sequence resets.
 */
export async function executeFile(
  generationResult: GenerationResult,
  schema: DatabaseSchema,
  orderedTables: string[],
  options: OutputOptions,
  progress: ProgressReporter,
  version: string,
): Promise<InsertionSummary> {
  const startTime = Date.now()
  const filePath = options.filePath!
  const rowsPerTable = new Map<string, number>()
  let totalRowsInserted = 0
  let deferredUpdatesApplied = 0
  const warnings = [...generationResult.warnings]
  const lines: string[] = []

  // 1. File header
  const tableCount = schema.tables.size
  lines.push(`-- Generated by seedforge v${version}`)
  lines.push(`-- Date: ${new Date().toISOString()}`)
  lines.push(`-- Database: ${schema.name}`)
  lines.push(`-- Tables: ${tableCount}`)
  lines.push('--')
  lines.push(`-- Execute with: psql -f ${filePath} <connection_string>`)
  lines.push('')

  // 2. Insert rows for each table in order
  for (const tableName of orderedTables) {
    const tableResult = generationResult.tables.get(tableName)
    if (!tableResult || tableResult.rows.length === 0) {
      continue
    }

    const tableDef = schema.tables.get(tableName)
    if (!tableDef) continue

    const rows = tableResult.rows
    const columns = getInsertableColumns(tableDef, rows[0])
    const totalRows = rows.length

    const batches = buildBatchedInserts(
      tableDef.name,
      tableDef.schema,
      columns,
      rows,
      options.batchSize,
    )

    progress.startTable(tableName, totalRows)

    // Table section comment
    lines.push(`-- Table: ${tableDef.schema}.${tableDef.name} (${totalRows} rows)`)
    lines.push('BEGIN;')

    for (const batch of batches) {
      lines.push(batch.sql)
      lines.push('')
    }

    lines.push('COMMIT;')
    lines.push('')

    progress.finishTable(tableName, totalRows, 0)
    rowsPerTable.set(tableName, totalRows)
    totalRowsInserted += totalRows
  }

  // 3. Deferred updates
  if (generationResult.deferredUpdates.length > 0) {
    lines.push('-- Deferred updates (two-phase insert for circular/self-referencing FKs)')

    // Group by table
    const updatesByTable = new Map<string, typeof generationResult.deferredUpdates>()
    for (const update of generationResult.deferredUpdates) {
      const existing = updatesByTable.get(update.tableName) ?? []
      existing.push(update)
      updatesByTable.set(update.tableName, existing)
    }

    for (const [tableName, updates] of updatesByTable) {
      const tableDef = schema.tables.get(tableName)
      if (!tableDef) continue

      lines.push('BEGIN;')
      for (const update of updates) {
        for (let i = 0; i < update.setColumns.length; i++) {
          const sql = buildUpdateSQL(
            tableDef.name,
            tableDef.schema,
            update.pkColumns,
            update.pkValues,
            update.setColumns[i],
            update.setValues[i],
          )
          lines.push(sql)
          deferredUpdatesApplied++
        }
      }
      lines.push('COMMIT;')
      lines.push('')
    }
  }

  // 4. Sequence resets (detected from schema metadata, no DB query needed)
  const sequenceResets = detectSequencesFromSchema(schema, orderedTables)
  if (sequenceResets.length > 0) {
    lines.push('-- Reset sequences')
    for (const seq of sequenceResets) {
      lines.push(buildSequenceResetSQL(
        seq.schemaName,
        seq.tableName,
        seq.columnName,
        seq.sequenceName,
      ))
    }
    lines.push('')
  }

  // 5. Write file
  try {
    await writeFile(filePath, lines.join('\n'), 'utf-8')
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err)
    throw new InsertionError(
      'SF4003',
      `Failed to write SQL file: ${filePath}: ${detail}`,
      [
        'Check that the directory exists and is writable',
        'Check available disk space',
      ],
      { filePath },
    )
  }

  const elapsedMs = Date.now() - startTime

  return {
    tablesSeeded: rowsPerTable.size,
    totalRowsInserted,
    rowsPerTable,
    deferredUpdatesApplied,
    sequencesReset: sequenceResets.length,
    elapsedMs,
    warnings,
    mode: OutputMode.FILE,
  }
}

/**
 * Detect sequences from schema metadata (for FILE mode without a DB connection).
 *
 * Looks for columns with:
 * - isAutoIncrement: true (serial columns)
 * - defaultValue containing nextval('...') (extracts sequence name)
 * - identity columns: constructs {table}_{column}_seq naming convention
 */
function detectSequencesFromSchema(
  schema: DatabaseSchema,
  orderedTables: string[],
): SequenceResetInfo[] {
  const sequences: SequenceResetInfo[] = []
  const seen = new Set<string>()

  for (const tableName of orderedTables) {
    const tableDef = schema.tables.get(tableName)
    if (!tableDef) continue

    for (const [, colDef] of tableDef.columns) {
      if (!colDef.isAutoIncrement) continue

      const key = `${tableDef.schema}.${tableDef.name}.${colDef.name}`
      if (seen.has(key)) continue
      seen.add(key)

      // Try to extract sequence name from default value
      let sequenceName: string | null = null
      if (colDef.defaultValue) {
        const match = /nextval\('([^']+)'/.exec(colDef.defaultValue)
        if (match) {
          sequenceName = match[1]
        }
      }

      // Fallback: use PostgreSQL naming convention
      if (!sequenceName) {
        sequenceName = `${tableDef.name}_${colDef.name}_seq`
      }

      sequences.push({
        tableName: tableDef.name,
        schemaName: tableDef.schema,
        columnName: colDef.name,
        sequenceName,
      })
    }
  }

  return sequences
}

/**
 * Determine which columns to insert for a table.
 */
function getInsertableColumns(
  tableDef: { columns: Map<string, { name: string; isGenerated: boolean }> },
  sampleRow: Record<string, unknown>,
): string[] {
  return Object.keys(sampleRow).filter((col) => {
    const colDef = tableDef.columns.get(col)
    return colDef && !colDef.isGenerated
  })
}
