import { describe, it, expect, afterEach } from 'vitest'
import { executeFile } from '../../executors/file.js'
import type { GenerationResult } from '../../../generate/types.js'
import type { DatabaseSchema, TableDef, ColumnDef } from '../../../types/schema.js'
import type { OutputOptions } from '../../types.js'
import { OutputMode } from '../../types.js'
import { ProgressReporter } from '../../progress.js'
import { NormalizedType } from '../../../types/schema.js'
import { readFile, unlink } from 'node:fs/promises'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

function makeColumn(name: string, overrides?: Partial<ColumnDef>): ColumnDef {
  return {
    name,
    dataType: NormalizedType.TEXT,
    nativeType: 'text',
    isNullable: true,
    hasDefault: false,
    defaultValue: null,
    isAutoIncrement: false,
    isGenerated: false,
    maxLength: null,
    numericPrecision: null,
    numericScale: null,
    enumValues: null,
    comment: null,
    ...overrides,
  }
}

function makeTable(name: string, schemaName: string, columnNames: string[]): TableDef {
  const columns = new Map<string, ColumnDef>()
  for (const col of columnNames) {
    columns.set(col, makeColumn(col, col === 'id' ? {
      isAutoIncrement: true,
      dataType: NormalizedType.INTEGER,
      defaultValue: `nextval('${name}_id_seq'::regclass)`,
    } : {}))
  }
  return {
    name,
    schema: schemaName,
    columns,
    primaryKey: { columns: ['id'], name: `${name}_pkey` },
    foreignKeys: [],
    uniqueConstraints: [],
    checkConstraints: [],
    indexes: [],
    comment: null,
  }
}

function makeSchema(tables: TableDef[]): DatabaseSchema {
  const tableMap = new Map<string, TableDef>()
  for (const t of tables) {
    tableMap.set(`${t.schema}.${t.name}`, t)
  }
  return {
    name: 'testdb',
    tables: tableMap,
    enums: new Map(),
    schemas: ['public'],
  }
}

function makeGenerationResult(
  tableData: Array<{ name: string; rows: Record<string, unknown>[] }>,
  deferredUpdates: GenerationResult['deferredUpdates'] = [],
): GenerationResult {
  const tables = new Map<string, { tableName: string; rows: Record<string, unknown>[]; generatedPKs: unknown[][] }>()
  for (const t of tableData) {
    tables.set(t.name, {
      tableName: t.name,
      rows: t.rows,
      generatedPKs: t.rows.map((r) => [r.id]),
    })
  }
  return { tables, deferredUpdates, warnings: [] }
}

describe('executeFile', () => {
  const tempFiles: string[] = []
  const progress = new ProgressReporter({ quiet: true, showProgress: false })

  afterEach(async () => {
    for (const f of tempFiles) {
      try {
        await unlink(f)
      } catch {
        // ignore
      }
    }
    tempFiles.length = 0
  })

  function tempPath(): string {
    const path = join(tmpdir(), `seedforge-test-${Date.now()}-${Math.random().toString(36).slice(2)}.sql`)
    tempFiles.push(path)
    return path
  }

  it('writes a valid SQL file with header and INSERT statements', async () => {
    const usersTable = makeTable('users', 'public', ['id', 'name'])
    const schema = makeSchema([usersTable])
    const filePath = tempPath()

    const genResult = makeGenerationResult([
      {
        name: 'public.users',
        rows: [
          { id: 1, name: 'Alice' },
          { id: 2, name: 'Bob' },
        ],
      },
    ])

    const options: OutputOptions = {
      mode: OutputMode.FILE,
      filePath,
      batchSize: 500,
      showProgress: false,
      quiet: true,
    }

    const summary = await executeFile(
      genResult,
      schema,
      ['public.users'],
      options,
      progress,
      '0.1.0',
    )

    expect(summary.tablesSeeded).toBe(1)
    expect(summary.totalRowsInserted).toBe(2)
    expect(summary.mode).toBe(OutputMode.FILE)

    const content = await readFile(filePath, 'utf-8')
    expect(content).toContain('-- Generated by seedforge v0.1.0')
    expect(content).toContain('-- Database: testdb')
    expect(content).toContain('BEGIN;')
    expect(content).toContain('COMMIT;')
    expect(content).toContain('INSERT INTO public.users')
    expect(content).toContain("'Alice'")
  })

  it('includes file header with date and execute instruction', async () => {
    const usersTable = makeTable('users', 'public', ['id', 'name'])
    const schema = makeSchema([usersTable])
    const filePath = tempPath()

    const genResult = makeGenerationResult([
      { name: 'public.users', rows: [{ id: 1, name: 'Test' }] },
    ])

    const options: OutputOptions = {
      mode: OutputMode.FILE,
      filePath,
      batchSize: 500,
      showProgress: false,
      quiet: true,
    }

    await executeFile(genResult, schema, ['public.users'], options, progress, '0.1.0')

    const content = await readFile(filePath, 'utf-8')
    expect(content).toContain('-- Date:')
    expect(content).toContain('-- Execute with: psql -f')
  })

  it('includes deferred updates section', async () => {
    const usersTable = makeTable('users', 'public', ['id', 'name', 'parent_id'])
    const schema = makeSchema([usersTable])
    const filePath = tempPath()

    const genResult = makeGenerationResult(
      [
        {
          name: 'public.users',
          rows: [{ id: 1, name: 'Alice', parent_id: null }],
        },
      ],
      [
        {
          tableName: 'public.users',
          pkColumns: ['id'],
          pkValues: [1],
          setColumns: ['parent_id'],
          setValues: [1],
        },
      ],
    )

    const options: OutputOptions = {
      mode: OutputMode.FILE,
      filePath,
      batchSize: 500,
      showProgress: false,
      quiet: true,
    }

    const summary = await executeFile(
      genResult,
      schema,
      ['public.users'],
      options,
      progress,
      '0.1.0',
    )

    expect(summary.deferredUpdatesApplied).toBe(1)
    const content = await readFile(filePath, 'utf-8')
    expect(content).toContain('-- Deferred updates')
    expect(content).toContain('UPDATE')
  })

  it('includes sequence reset section', async () => {
    const usersTable = makeTable('users', 'public', ['id', 'name'])
    const schema = makeSchema([usersTable])
    const filePath = tempPath()

    const genResult = makeGenerationResult([
      { name: 'public.users', rows: [{ id: 1, name: 'Test' }] },
    ])

    const options: OutputOptions = {
      mode: OutputMode.FILE,
      filePath,
      batchSize: 500,
      showProgress: false,
      quiet: true,
    }

    await executeFile(genResult, schema, ['public.users'], options, progress, '0.1.0')

    const content = await readFile(filePath, 'utf-8')
    expect(content).toContain('-- Reset sequences')
    expect(content).toContain('setval')
    expect(content).toContain('users_id_seq')
  })

  it('throws InsertionError SF4003 on file write failure', async () => {
    const usersTable = makeTable('users', 'public', ['id', 'name'])
    const schema = makeSchema([usersTable])

    const genResult = makeGenerationResult([
      { name: 'public.users', rows: [{ id: 1, name: 'Test' }] },
    ])

    const options: OutputOptions = {
      mode: OutputMode.FILE,
      filePath: '/nonexistent/dir/output.sql',
      batchSize: 500,
      showProgress: false,
      quiet: true,
    }

    try {
      await executeFile(genResult, schema, ['public.users'], options, progress, '0.1.0')
      expect.fail('Should have thrown')
    } catch (err) {
      expect(err).toBeInstanceOf(Error)
      expect((err as { code: string }).code).toBe('SF4003')
    }
  })
})
